import type { ChecklistTask, Worker } from '../types'

export const mockWorkers: Worker[] = [
  { id: 'worker-ava', name: 'Ava' },
  { id: 'worker-ben', name: 'Ben' },
  { id: 'worker-mia', name: 'Mia' },
]

export const mockDailyClosingTasks: ChecklistTask[] = [
  {
    id: 'daily-clean-beer-taps',
    title: 'Clean beer taps',
    description: 'Wipe tap handles, spouts, and drip trays.',
    section: 'Bar',
    taskType: 'daily_closing',
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'daily-wipe-bar-tops',
    title: 'Wipe bar tops',
    description: 'Clear spills, sticky patches, and service areas.',
    section: 'Bar',
    taskType: 'daily_closing',
    sortOrder: 20,
    isActive: true,
  },
  {
    id: 'daily-empty-glasswasher',
    title: 'Empty glasswasher',
    description: 'Remove racks, drain, and leave door open.',
    section: 'Bar',
    taskType: 'daily_closing',
    sortOrder: 30,
    isActive: true,
  },
  {
    id: 'daily-mop-behind-bar',
    title: 'Mop behind bar',
    section: 'Bar',
    taskType: 'daily_closing',
    sortOrder: 40,
    isActive: true,
  },
  {
    id: 'daily-secure-spirits',
    title: 'Secure spirits',
    description: 'Lock premium bottles and back bar stock.',
    section: 'Bar',
    taskType: 'daily_closing',
    sortOrder: 50,
    isActive: true,
    isCritical: true,
  },
  {
    id: 'daily-turn-off-music',
    title: 'Turn off music and screens',
    section: 'Bar',
    taskType: 'daily_closing',
    sortOrder: 60,
    isActive: true,
    isCritical: true,
  },
  {
    id: 'daily-clear-floor-glasses',
    title: 'Clear floor glasses',
    section: 'Floor',
    taskType: 'daily_closing',
    sortOrder: 70,
    isActive: true,
  },
  {
    id: 'daily-check-toilets',
    title: 'Check toilets',
    description: 'Remove rubbish and report any maintenance issues.',
    section: 'Floor',
    taskType: 'daily_closing',
    sortOrder: 80,
    isActive: true,
  },
  {
    id: 'daily-sweep-floor',
    title: 'Sweep floor',
    section: 'Floor',
    taskType: 'daily_closing',
    sortOrder: 90,
    isActive: true,
  },
  {
    id: 'daily-take-out-bins',
    title: 'Take out bins',
    section: 'Cleaning',
    taskType: 'daily_closing',
    sortOrder: 100,
    isActive: true,
  },
  {
    id: 'daily-clean-service-sink',
    title: 'Clean service sink',
    section: 'Cleaning',
    taskType: 'daily_closing',
    sortOrder: 110,
    isActive: true,
  },
  {
    id: 'daily-sanitise-tools',
    title: 'Sanitise bar tools',
    section: 'Cleaning',
    taskType: 'daily_closing',
    sortOrder: 120,
    isActive: true,
  },
  {
    id: 'daily-restock-fridges',
    title: 'Restock fridges',
    description: 'Face labels forward and rotate older stock to the front.',
    section: 'Stock',
    taskType: 'daily_closing',
    sortOrder: 130,
    isActive: true,
  },
  {
    id: 'daily-refill-napkins-straws',
    title: 'Refill napkins and straws',
    section: 'Stock',
    taskType: 'daily_closing',
    sortOrder: 140,
    isActive: true,
  },
  {
    id: 'daily-check-keg-room',
    title: 'Check keg room',
    description: 'Confirm no leaks and leave walkway clear.',
    section: 'Stock',
    taskType: 'daily_closing',
    sortOrder: 150,
    isActive: true,
  },
  {
    id: 'daily-top-up-garnishes',
    title: 'Top up sealed garnishes',
    section: 'Stock',
    taskType: 'daily_closing',
    sortOrder: 160,
    isActive: true,
  },
  {
    id: 'daily-count-till',
    title: 'Count till',
    section: 'Admin',
    taskType: 'daily_closing',
    sortOrder: 170,
    isActive: true,
    isCritical: true,
  },
  {
    id: 'daily-submit-close-notes',
    title: 'Submit close notes',
    description: 'Record shortages, incidents, and maintenance issues.',
    section: 'Admin',
    taskType: 'daily_closing',
    sortOrder: 180,
    isActive: true,
    isCritical: true,
  },
  {
    id: 'daily-lock-back-door',
    title: 'Lock doors',
    section: 'Admin',
    taskType: 'daily_closing',
    sortOrder: 190,
    isActive: true,
    isCritical: true,
  },
  {
    id: 'daily-final-walk-through',
    title: 'Final venue walk-through',
    section: 'Admin',
    taskType: 'daily_closing',
    sortOrder: 200,
    isActive: true,
    isCritical: true,
  },
]

export const mockWeeklyCleaningTasks: ChecklistTask[] = [
  {
    id: 'weekly-deep-clean-glasswasher',
    title: 'Deep clean glasswasher',
    section: 'Cleaning',
    taskType: 'weekly_cleaning',
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'weekly-clean-fridge-seals',
    title: 'Clean fridge seals',
    section: 'Cleaning',
    taskType: 'weekly_cleaning',
    sortOrder: 20,
    isActive: true,
  },
  {
    id: 'weekly-wipe-bottle-shelves',
    title: 'Wipe bottle shelves',
    section: 'Bar',
    taskType: 'weekly_cleaning',
    sortOrder: 30,
    isActive: true,
  },
  {
    id: 'weekly-clean-speed-pourers',
    title: 'Clean speed pourers',
    section: 'Bar',
    taskType: 'weekly_cleaning',
    sortOrder: 40,
    isActive: true,
  },
  {
    id: 'weekly-clean-ice-well',
    title: 'Clean ice well',
    section: 'Bar',
    taskType: 'weekly_cleaning',
    sortOrder: 50,
    isActive: true,
  },
  {
    id: 'weekly-detail-beer-taps',
    title: 'Detail beer taps',
    section: 'Bar',
    taskType: 'weekly_cleaning',
    sortOrder: 60,
    isActive: true,
  },
  {
    id: 'weekly-clean-under-mats',
    title: 'Clean under mats',
    section: 'Cleaning',
    taskType: 'weekly_cleaning',
    sortOrder: 70,
    isActive: true,
  },
  {
    id: 'weekly-wipe-walls-behind-bar',
    title: 'Wipe walls behind bar',
    section: 'Cleaning',
    taskType: 'weekly_cleaning',
    sortOrder: 80,
    isActive: true,
  },
  {
    id: 'weekly-dust-high-shelves',
    title: 'Dust high shelves',
    section: 'Other',
    taskType: 'weekly_cleaning',
    sortOrder: 90,
    isActive: true,
  },
  {
    id: 'weekly-audit-backup-stock',
    title: 'Audit backup stock',
    section: 'Stock',
    taskType: 'weekly_cleaning',
    sortOrder: 100,
    isActive: true,
  },
]
